import type { Metadata } from "next";
import { Outfit, Lacquer } from "next/font/google";
import "./globals.css";
import Layout from "@/components/layout/Layout";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const lacquer = Lacquer({
  variable: "--font-lacquer",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${lacquer.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
